---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fossorial-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.fossorial.io
  timeout: 2m

